name: CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test --no-daemon
      - name: Report test summary
        id: summary
        if: always()
        run: |
          total=$(grep -o 'tests="[0-9]*"' build/test-results/test/TEST-*.xml | grep -o '[0-9]*' | paste -sd+ - | bc)
          failed=$(grep -o 'failures="[0-9]*"' build/test-results/test/TEST-*.xml | grep -o '[0-9]*' | paste -sd+ - | bc)
          skipped=$(grep -o 'skipped="[0-9]*"' build/test-results/test/TEST-*.xml | grep -o '[0-9]*' | paste -sd+ - | bc)
          echo "Total tests: $total" >> $GITHUB_STEP_SUMMARY
          echo "Failures: $failed" >> $GITHUB_STEP_SUMMARY
          echo "Skipped: $skipped" >> $GITHUB_STEP_SUMMARY
          echo "total=$total" >> $GITHUB_OUTPUT
          echo "failed=$failed" >> $GITHUB_OUTPUT
          echo "skipped=$skipped" >> $GITHUB_OUTPUT

      - name: Publish check summary
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const total = '${{ steps.summary.outputs.total }}';
            const failed = '${{ steps.summary.outputs.failed }}';
            const skipped = '${{ steps.summary.outputs.skipped }}';
            const summary = `### Test Results\n- Total: ${total}\n- Failed: ${failed}\n- Skipped: ${skipped}`;
            const conclusion = failed === '0' ? 'success' : 'failure';
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Test Results',
              head_sha: context.sha,
              status: 'completed',
              conclusion,
              completed_at: new Date().toISOString(),
              output: {
                title: 'Test Results',
                summary
              }
            });
